package _01javaLangObjectClass;

class Person {
	private int rollNumber;

	public Person(int rollNumber) {
		super();
		this.rollNumber = rollNumber;
	}

	public int getRollNumber() {
		return rollNumber;
	}

	/*
	 * toString method is used to get string representation of an object
	 */@Override
	public String toString() {
		return "Person Roll Number is " + rollNumber;
	}

	/*
	 * hashCode method is used to assign unique number to object generated by jvm which is
	 * nothing but hashcode, hashcode dosen't represent address of object and
	 * hashcode is used while saving objects into hashing related data
	 * structures like HashMap, HashSet. Main advantage of saving objects based
	 * on hascode is search operation will become easy
	 */
	public int hashCode() {
		return rollNumber;
	}
}

public class _02HashCodeMethodDemo {

	public static void main(String[] args) {
		Person person1 = new Person(1234);
		Person person2 = new Person(5678);

		System.out.println(person1);
		System.out.println(person2);
		System.out.println();
		System.out.println("hashcode of person1 is " + person1.hashCode());
		System.out.println("hashcode of person2 is " + person1.hashCode());
	}

}
